Use Go project gofmt checker.

diff --git a/script/failfmt b/script/failfmt
--- a/script/failfmt
+++ b/script/failfmt
@@ -1,7 +1,23 @@
-#!/bin/bash
-if gofmt -l . 2>&1 | grep '^'; then
-  echo "You need to format your code with gofmt!"
-  exit 1
-else
-  exit 0
-fi
+#!/bin/sh
+# Copyright 2012 The Go Authors. All rights reserved.
+# Use of this source code is governed by a BSD-style
+# license that can be found in the LICENSE file.
+
+# git gofmt pre-commit hook
+#
+# To use, store as .git/hooks/pre-commit inside your repository and make sure
+# it has execute permissions.
+#
+# This script does not handle file names that contain spaces.
+
+unformatted=$(gofmt -l *.go)
+[ -z "$unformatted" ] && exit 0
+
+# Some files are not gofmt'd. Print message and fail.
+
+echo >&2 "Go files must be formatted with gofmt. Please run:"
+for fn in $unformatted; do
+    echo >&2 "  gofmt -w $PWD/$fn"
+done
+
+exit 1
